version: '3.2'


services:

  object-classifier:
    build:
      context: ./src

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/object-classification/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/object-classification/rabbitmq/log/:/var/log/rabbitmq